class GeneratesMeshMixin:
    """Provides functionality for interfaces that generate their own mesh (cells).

    This mixin ensures that an interface can store and manipulate a generated
    mesh, which will later be integrated into the main assembled mesh.

    Attributes:
        interface_mesh: The mesh generated by this interface. This is typically
            an object representing a collection of cells and nodes.

    Example:
        >>> class MyMeshInterface(GeneratesMeshMixin):
        ...     def build_mesh(self, num_cells: int = 10):
        ...         self.interface_mesh = f"Mesh with {num_cells} cells"
        ...     def integrate_mesh(self, assembled_mesh, name="default"):
        ...         assembled_mesh[name] = self.interface_mesh
        >>> main_mesh = {}
        >>> interface = MyMeshInterface()
        >>> interface.build_mesh(num_cells=5)
        >>> interface.integrate_mesh(main_mesh, name="my_interface_mesh")
        >>> print(main_mesh["my_interface_mesh"])
        Mesh with 5 cells
    """

    interface_mesh = None  # type: ignore

    def build_mesh(self, **kwargs):
        """Generates and populates the mesh specific to this interface.

        This method must be overridden by any concrete class inheriting this
        mixin. It is responsible for creating and assigning an object to the
        `interface_mesh` attribute.

        Args:
            **kwargs: Arbitrary keyword arguments that may be required for
                mesh generation (e.g., density, resolution).

        Raises:
            NotImplementedError: If the method is not overridden in a concrete class.

        Example:
            >>> class MyMeshBuilder(GeneratesMeshMixin):
            ...     def build_mesh(self, num_cells: int = 10):
            ...         self.interface_mesh = f"Mesh with {num_cells} cells."
            ...         print(self.interface_mesh)
            >>> builder = MyMeshBuilder()
            >>> builder.build_mesh(num_cells=7)
            Mesh with 7 cells.
        """
        raise NotImplementedError

    def integrate_mesh(self, assembled_mesh, **kwargs):
        """Integrates the generated interface mesh into the main assembled mesh.

        This method is optional and provides a hook for concrete implementations
        to merge or attach `interface_mesh` to the global `assembled_mesh`.
        If not overridden, it performs no operation.

        Args:
            assembled_mesh: The global mesh object to which the interface mesh
                should be integrated. The exact type depends on the solver.
            **kwargs: Arbitrary keyword arguments that may be required for
                the integration process.

        Example:
            >>> class MyMeshIntegrator(GeneratesMeshMixin):
            ...     def build_mesh(self):
            ...         self.interface_mesh = "LocalMesh"
            ...     def integrate_mesh(self, main_mesh_dict, key="interface"):
            ...         main_mesh_dict[key] = self.interface_mesh
            ...         print(f"Integrated '{self.interface_mesh}' into main_mesh_dict['{key}'].")
            >>> global_mesh = {}
            >>> integrator = MyMeshIntegrator()
            >>> integrator.build_mesh()
            >>> integrator.integrate_mesh(global_mesh, key="component_mesh")
            Integrated 'LocalMesh' into main_mesh_dict['component_mesh'].
            >>> print(global_mesh)
            {'component_mesh': 'LocalMesh'}
        """
        pass


class GeneratesNodesMixin:
    """Provides functionality for interfaces that only generate nodes, not cells.

    This mixin is designed for components that contribute discrete nodes to the
    overall structural model, without forming new elements (cells).

    Attributes:
        new_nodes (list): A list of newly generated node objects or data
            structures. These nodes are expected to be integrated into the
            main assembled mesh.

    Example:
        >>> class MyNodeSource(GeneratesNodesMixin):
        ...     def build_nodes(self, count: int = 2):
        ...         self.new_nodes = [f"Node_{i}" for i in range(count)]
        ...     def integrate_nodes(self, mesh_node_list):
        ...         mesh_node_list.extend(self.new_nodes)
        >>> global_node_list = []
        >>> source = MyNodeSource()
        >>> source.build_nodes(count=3)
        >>> source.integrate_nodes(global_node_list)
        >>> print(global_node_list)
        ['Node_0', 'Node_1', 'Node_2']
    """

    new_nodes = []  # type: ignore

    def build_nodes(self, **kwargs):
        """Generates and populates the `new_nodes` list for this interface.

        This method must be overridden by any concrete class inheriting this
        mixin. It is responsible for creating the node data that will later
        be integrated into the global mesh.

        Args:
            **kwargs: Arbitrary keyword arguments that may be required for
                node generation (e.g., coordinates, count).

        Raises:
            NotImplementedError: If the method is not overridden in a concrete class.

        Example:
            >>> class MyNodeGenerator(GeneratesNodesMixin):
            ...     def build_nodes(self, num_nodes: int = 2):
            ...         print(f"Generating {num_nodes} nodes.")
            ...         for i in range(num_nodes):
            ...             self.new_nodes.append(f"Node_{i+1}_XYZ")
            >>> generator = MyNodeGenerator()
            >>> generator.build_nodes(num_nodes=3)
            Generating 3 nodes.
            >>> print(generator.new_nodes)
            ['Node_1_XYZ', 'Node_2_XYZ', 'Node_3_XYZ']
        """
        raise NotImplementedError

    def integrate_nodes(self, assembled_mesh, **kwargs):
        """Integrates the generated `new_nodes` into the main assembled mesh.

        This method provides a hook for concrete implementations to add the
        `new_nodes` to the global `assembled_mesh`. If not overridden, it
        performs no operation.

        Args:
            assembled_mesh: The global mesh object to which the new nodes
                should be integrated.
            **kwargs: Arbitrary keyword arguments that may be required for
                the integration process.

        Example:
            >>> class MyNodeIntegrator(GeneratesNodesMixin):
            ...     def build_nodes(self):
            ...         self.new_nodes = ["NodeA", "NodeB"]
            ...     def integrate_nodes(self, main_mesh_list):
            ...         main_mesh_list.extend(self.new_nodes)
            ...         print(f"Integrated {self.new_nodes} into main_mesh_list.")
            >>> main_mesh_nodes = []
            >>> integrator = MyNodeIntegrator()
            >>> integrator.build_nodes()
            >>> integrator.integrate_nodes(main_mesh_nodes)
            Integrated ['NodeA', 'NodeB'] into main_mesh_list.
            >>> print(main_mesh_nodes)
            ['NodeA', 'NodeB']
        """
        pass


class GeneratesConstraintsMixin:
    """Provides functionality for interfaces that create constraints (multi-point or single-point).

    This mixin enables an interface to define and manage various types of
    constraints that will be applied to the structural model.

    Attributes:
        constraints (list): A list of constraint objects (e.g., SPConstraint,
            MPConstraint) generated by this interface. These are intended
            to be registered with global constraint managers.

    Example:
        >>> class MyConstraintInterface(GeneratesConstraintsMixin):
        ...     def build_constraints(self, node_ids: list):
        ...         self.constraints = [f"SPConstraint_on_{nid}" for nid in node_ids]
        ...     def register_constraints(self):
        ...         print(f"Registering: {self.constraints}")
        >>> interface = MyConstraintInterface()
        >>> interface.build_constraints(node_ids=[1, 5, 10])
        >>> interface.register_constraints()
        Registering: ['SPConstraint_on_1', 'SPConstraint_on_5', 'SPConstraint_on_10']
    """

    constraints = []  # type: ignore

    def build_constraints(self, **kwargs):
        """Generates and populates the `constraints` list for this interface.

        This method must be overridden by any concrete class inheriting this
        mixin. It is responsible for creating the constraint objects that
        will later be registered with global managers.

        Args:
            **kwargs: Arbitrary keyword arguments that may be required for
                constraint generation (e.g., node IDs, degrees of freedom).

        Raises:
            NotImplementedError: If the method is not overridden in a concrete class.

        Example:
            >>> class MyConstraintGenerator(GeneratesConstraintsMixin):
            ...     def build_constraints(self, node_id: int = 1):
            ...         print(f"Generating constraint for node {node_id}.")
            ...         self.constraints.append(f"Constraint_on_Node_{node_id}")
            >>> generator = MyConstraintGenerator()
            >>> generator.build_constraints(node_id=10)
            Generating constraint for node 10.
            >>> print(generator.constraints)
            ['Constraint_on_Node_10']
        """
        raise NotImplementedError

    def register_constraints(self):
        """Pushes the generated constraints to the global constraint managers.

        This method provides a hook for concrete implementations to register
        the `constraints` stored in this interface with the appropriate
        multi-point (MP) or single-point (SP) constraint managers in the
        overall system.

        Example:
            >>> class MockMPManager:
            ...     def __init__(self): self.registered = []
            ...     def add_constraint(self, c): self.registered.append(c)
            ...     def __repr__(self): return f"MockMPManager({self.registered})"
            >>> class MyConstraintRegistrar(GeneratesConstraintsMixin):
            ...     def build_constraints(self):
            ...         self.constraints.extend(["C1", "C2"])
            ...     def register_constraints(self):
            ...         # In a real system, you'd access global managers
            ...         mp_manager = MockMPManager()
            ...         for c in self.constraints:
            ...             mp_manager.add_constraint(c)
            ...         print(f"Registered {len(self.constraints)} constraints: {mp_manager.registered}")
            >>> registrar = MyConstraintRegistrar()
            >>> registrar.build_constraints()
            >>> registrar.register_constraints()
            Registered 2 constraints: ['C1', 'C2']
        """
        pass


class HandlesDecompositionMixin:
    """Provides functionality for interfaces that react to mesh repartitioning.

    This mixin allows an interface to be notified and update its internal
    state whenever the global mesh or its associated data arrays are
    repartitioned or updated by the core system.

    Example:
        >>> class MyPartitionHandler(HandlesDecompositionMixin):
        ...     def __init__(self):
        ...         self.last_known_partition_id = None
        ...     def on_partition_update(self, assembled_mesh, new_partition_id: int = 0):
        ...         self.last_known_partition_id = new_partition_id
        ...         print(f"Updated for mesh '{assembled_mesh}' to partition ID {new_partition_id}.")
        >>> handler = MyPartitionHandler()
        >>> handler.on_partition_update("Mesh_A", new_partition_id=1)
        Updated for mesh 'Mesh_A' to partition ID 1.
        >>> print(handler.last_known_partition_id)
        1
    """

    def on_partition_update(self, assembled_mesh, **kwargs):
        """Called to update the internal state after the core arrays of the mesh change.

        This method is invoked by the system whenever the global `assembled_mesh`
        is repartitioned, redistributed, or its underlying data structures are
        significantly altered. Concrete implementations should override this
        to update any cached data or references based on the new mesh state.

        Args:
            assembled_mesh: The updated global mesh object.
            **kwargs: Arbitrary keyword arguments providing additional context
                about the partition update (e.g., new partition ID, changed elements).

        Example:
            >>> class MyDataUpdater(HandlesDecompositionMixin):
            ...     def __init__(self):
            ...         self.cached_element_count = 0
            ...     def on_partition_update(self, current_mesh_info, repartition_event: bool = True):
            ...         self.cached_element_count = current_mesh_info.get("num_elements", 0)
            ...         print(f"Mesh repartitioned ({repartition_event}). Cached element count: {self.cached_element_count}")
            >>> updater = MyDataUpdater()
            >>> updater.on_partition_update({"name": "mesh_part_1", "num_elements": 100}, repartition_event=True)
            Mesh repartitioned (True). Cached element count: 100
            >>> updater.on_partition_update({"name": "mesh_part_2", "num_elements": 150})
            Mesh repartitioned (True). Cached element count: 150
        """
        pass