class GeneratesMeshMixin:
    """Mixin for interfaces that must create their own mesh (cells).

    This mixin provides a standard interface for components responsible
    for generating and integrating a mesh into a larger structural model.

    Attributes:
        interface_mesh: The mesh generated by this interface. Its exact type
            is dependent on the implementation but typically represents
            a collection of cells and associated data.

    Example:
        >>> class MyMeshGenerator(GeneratesMeshMixin):
        ...     def build_mesh(self, resolution=10):
        ...         # Simulate mesh generation
        ...         self.interface_mesh = f"Generated {resolution}x{resolution} mesh"
        >>> generator = MyMeshGenerator()
        >>> generator.build_mesh(resolution=5)
        >>> print(generator.interface_mesh)
        Generated 5x5 mesh
    """

    interface_mesh = None  # type: ignore

    def build_mesh(self, **kwargs):
        """Populate `interface_mesh` with generated mesh data.

        This method must be overridden by concrete implementations to define
        how the mesh is constructed. It is expected to set the `interface_mesh`
        attribute.

        Args:
            **kwargs: Arbitrary keyword arguments that may be passed to
                configure mesh generation.

        Raises:
            NotImplementedError: If the method is not overridden by a subclass.

        Example:
            >>> class MyMeshGenerator(GeneratesMeshMixin):
            ...     def build_mesh(self, resolution=10):
            ...         # Simulate mesh generation
            ...         self.interface_mesh = f"{resolution}x{resolution}_mesh"
            >>> generator = MyMeshGenerator()
            >>> generator.build_mesh(resolution=5)
            >>> print(generator.interface_mesh)
            5x5_mesh
        """
        raise NotImplementedError

    def integrate_mesh(self, assembled_mesh, **kwargs):
        """Optional: merge or attach the generated mesh to the main assembled mesh.

        This method can be overridden to define how the `interface_mesh`
        is incorporated into the `assembled_mesh`. A common use case is
        adding new cells or updating existing ones.

        Args:
            assembled_mesh: The main mesh object of the structural model,
                to which this interface's mesh should be integrated.
            **kwargs: Arbitrary keyword arguments for integration.

        Example:
            >>> class MyMeshIntegrator(GeneratesMeshMixin):
            ...     def build_mesh(self):
            ...         self.interface_mesh = {"cells": ["c1", "c2"]}
            ...     def integrate_mesh(self, assembled_mesh, offset=0):
            ...         # Simulate adding cells to assembled_mesh
            ...         assembled_mesh["cells"].extend(self.interface_mesh["cells"])
            ...         assembled_mesh["offset"] = offset
            >>> main_mesh = {"cells": []}
            >>> integrator = MyMeshIntegrator()
            >>> integrator.build_mesh()
            >>> integrator.integrate_mesh(main_mesh, offset=10)
            >>> print(main_mesh)
            {'cells': ['c1', 'c2'], 'offset': 10}
        """
        pass


class GeneratesNodesMixin:
    """Mixin for interfaces that only add nodes (no cells).

    This mixin provides an interface for components that are responsible
    for generating and integrating new nodes into a larger structural model,
    without necessarily defining new elements or cells.

    Attributes:
        new_nodes (list): A list of newly generated nodes. Each node's
            representation (e.g., dictionary, object) is implementation-specific.

    Example:
        >>> class MyNodeGenerator(GeneratesNodesMixin):
        ...     def build_nodes(self, count=2):
        ...         self.new_nodes = [{"id": i, "coords": [i, 0, 0]} for i in range(count)]
        >>> generator = MyNodeGenerator()
        >>> generator.build_nodes(count=3)
        >>> print(generator.new_nodes)
        [{'id': 0, 'coords': [0, 0, 0]}, {'id': 1, 'coords': [1, 0, 0]}, {'id': 2, 'coords': [2, 0, 0]}]
    """

    new_nodes = []  # type: ignore

    def build_nodes(self, **kwargs):
        """Populate `new_nodes` with generated node data.

        This method must be overridden by concrete implementations to define
        how new nodes are constructed. It is expected to populate the
        `new_nodes` attribute.

        Args:
            **kwargs: Arbitrary keyword arguments that may be passed to
                configure node generation.

        Raises:
            NotImplementedError: If the method is not overridden by a subclass.

        Example:
            >>> class MyNodeGenerator(GeneratesNodesMixin):
            ...     def build_nodes(self, count=2):
            ...         self.new_nodes = [{"id": i, "coords": [i, 0, 0]} for i in range(count)]
            >>> generator = MyNodeGenerator()
            >>> generator.build_nodes(count=3)
            >>> print(generator.new_nodes)
            [{'id': 0, 'coords': [0, 0, 0]}, {'id': 1, 'coords': [1, 0, 0]}, {'id': 2, 'coords': [2, 0, 0]}]
        """
        raise NotImplementedError

    def integrate_nodes(self, assembled_mesh, **kwargs):
        """Optional: merge or attach the generated nodes to the main assembled mesh.

        This method can be overridden to define how the `new_nodes` are
        incorporated into the `assembled_mesh`. This often involves adding
        them to a global node list or a node dictionary.

        Args:
            assembled_mesh: The main mesh object of the structural model,
                to which this interface's nodes should be integrated.
            **kwargs: Arbitrary keyword arguments for integration.

        Example:
            >>> class MyNodeIntegrator(GeneratesNodesMixin):
            ...     def build_nodes(self):
            ...         self.new_nodes = [{"id": 1, "pos": [1,0,0]}, {"id": 2, "pos": [2,0,0]}]
            ...     def integrate_nodes(self, assembled_mesh):
            ...         # Simulate adding nodes to assembled_mesh's node collection
            ...         assembled_mesh["nodes"].extend(self.new_nodes)
            >>> main_mesh = {"nodes": []}
            >>> integrator = MyNodeIntegrator()
            >>> integrator.build_nodes()
            >>> integrator.integrate_nodes(main_mesh)
            >>> print(main_mesh)
            {'nodes': [{'id': 1, 'pos': [1, 0, 0]}, {'id': 2, 'pos': [2, 0, 0]}]}
        """
        pass


class GeneratesConstraintsMixin:
    """Mixin for interfaces that create multi-point (mp) or single-point (sp) constraints.

    This mixin provides a standard interface for components responsible
    for defining and registering structural constraints.

    Attributes:
        constraints (list): A list of generated constraint objects. Each object
            should typically contain information about the constrained degrees
            of freedom, node IDs, and constraint type (e.g., MP or SP).

    Example:
        >>> class MyConstraintGenerator(GeneratesConstraintsMixin):
        ...     def build_constraints(self, fixed_node_id=1):
        ...         # Simulate creating a single-point constraint
        ...         self.constraints = [{"type": "SP", "node": fixed_node_id, "dofs": [0,1,2]}]
        >>> generator = MyConstraintGenerator()
        >>> generator.build_constraints(fixed_node_id=5)
        >>> print(generator.constraints)
        [{'type': 'SP', 'node': 5, 'dofs': [0, 1, 2]}]
    """

    constraints = []  # type: ignore

    def build_constraints(self, **kwargs):
        """Populate `constraints` with generated constraint data.

        This method must be overridden by concrete implementations to define
        how constraints are constructed. It is expected to populate the
        `constraints` attribute.

        Args:
            **kwargs: Arbitrary keyword arguments that may be passed to
                configure constraint generation.

        Raises:
            NotImplementedError: If the method is not overridden by a subclass.

        Example:
            >>> class MyConstraintGenerator(GeneratesConstraintsMixin):
            ...     def build_constraints(self, fixed_node_id=1):
            ...         # Simulate creating a single-point constraint
            ...         self.constraints = [{"type": "SP", "node": fixed_node_id, "dofs": [0,1,2]}]
            >>> generator = MyConstraintGenerator()
            >>> generator.build_constraints(fixed_node_id=5)
            >>> print(generator.constraints)
            [{'type': 'SP', 'node': 5, 'dofs': [0, 1, 2]}]
        """
        raise NotImplementedError

    def register_constraints(self):
        """Push constraints to the global managers (MP/SP).

        This method is responsible for taking the `constraints` generated
        by `build_constraints` and registering them with the appropriate
        global constraint managers in the structural analysis framework.

        Example:
            >>> class MockSPManager:
            ...     def __init__(self): self.registered = []
            ...     def register(self, constraint): self.registered.append(constraint)
            >>> sp_manager = MockSPManager()
            >>>
            >>> class MyConstraintRegistrar(GeneratesConstraintsMixin):
            ...     def build_constraints(self):
            ...         self.constraints = [{"type": "SP", "node": 1, "dofs": [0]}]
            ...     def register_constraints(self):
            ...         # In a real system, this would interact with a global SP manager
            ...         for c in self.constraints:
            ...             if c["type"] == "SP":
            ...                 sp_manager.register(c)
            >>> registrar = MyConstraintRegistrar()
            >>> registrar.build_constraints()
            >>> registrar.register_constraints()
            >>> print(sp_manager.registered)
            [{'type': 'SP', 'node': 1, 'dofs': [0]}]
        """
        pass


class HandlesDecompositionMixin:
    """Mixin that is notified when the mesh is repartitioned and may react.

    This mixin provides an interface for components that need to update their
    internal state or data structures when the global mesh of the structural
    model undergoes repartitioning or other significant changes in its core
    arrays.

    Attributes:
        (None): This mixin itself does not introduce specific public attributes
            but expects concrete implementations to manage their own internal
            state that might react to partition updates.

    Example:
        >>> class MyDecompositionHandler(HandlesDecompositionMixin):
        ...     def __init__(self):
        ...         self.local_elements = []
        ...     def on_partition_update(self, assembled_mesh, partition_id=0):
        ...         # Simulate updating local elements based on the new partition
        ...         self.local_elements = [
        ...             e for e in assembled_mesh.get_all_elements()
        ...             if e.partition == partition_id
        ...         ]
        ...         print(f"Updated local elements for partition {partition_id}: {self.local_elements}")
        >>> class MockAssembledMesh:
        ...     def get_all_elements(self):
        ...         class Element:
        ...             def __init__(self, _id, _partition):
        ...                 self.id = _id
        ...                 self.partition = _partition
        ...             def __repr__(self): return f"E{self.id}P{self.partition}"
        ...         return [Element(1,0), Element(2,1), Element(3,0)]
        >>> handler = MyDecompositionHandler()
        >>> handler.on_partition_update(MockAssembledMesh(), partition_id=0)
        Updated local elements for partition 0: [E1P0, E3P0]
    """

    def on_partition_update(self, assembled_mesh, **kwargs):
        """Update internal state after Core arrays change.

        This method is called by the framework when a significant change,
        such as mesh repartitioning, occurs in the `assembled_mesh`'s
        underlying data structures. Implementations should use this to
        synchronize their own data with the new mesh state.

        Args:
            assembled_mesh: The main mesh object of the structural model,
                which has just been repartitioned or updated.
            **kwargs: Arbitrary keyword arguments providing additional
                context about the partition update.

        Example:
            >>> class MyDecompositionHandler(HandlesDecompositionMixin):
            ...     def __init__(self):
            ...         self.local_elements = []
            ...     def on_partition_update(self, assembled_mesh, partition_id=0):
            ...         # Simulate updating local elements based on the new partition
            ...         self.local_elements = [
            ...             e for e in assembled_mesh.get_all_elements()
            ...             if e.partition == partition_id
            ...         ]
            ...         print(f"Updated local elements for partition {partition_id}: {self.local_elements}")
            >>> class MockAssembledMesh:
            ...     def get_all_elements(self):
            ...         class Element:
            ...             def __init__(self, _id, _partition):
            ...                 self.id = _id
            ...                 self.partition = _partition
            ...             def __repr__(self): return f"E{self.id}P{self.partition}"
            ...         return [Element(1,0), Element(2,1), Element(3,0)]
            >>> handler = MyDecompositionHandler()
            >>> handler.on_partition_update(MockAssembledMesh(), partition_id=0)
            Updated local elements for partition 0: [E1P0, E3P0]
        """
        pass